### PR TITLE
Protect references of attributes output through BMI

### PR DESCRIPTION
**Pull request by mdpiper**
The pyDeltaRCM model attributes `stage`, `depth`, and `eta` are mapped to BMI output variables in the BmiDelta class. However, when the model is updated, information isn't being passed from these attributes to the BMI variables. It appears that the references for these attributes were being overwritten by methods in the Tools class. To protect the references, I replaced assignment statements with array subscripting statements. There's likely a better way to handle this problem (e.g., through properties), but this way seems to work.

### CODE REVIEW

**Comment by mdpiper** [comment]
Hi, @mperignon! I looked into other ways to get pyDeltaRCM to work with BMI that didn't involve modifying the pyDeltaRCM code. The only other way that worked for me is to use properties in the `pyDeltaRCM` class, which is still intrusive. As @mcflugen suggested, this may be a problem with BMI. So, I'm stuck. May I reopen this PR, noting that it's unfair for BMI to need this internal change to your code?

**Comment by mcflugen** [comment]
If I'm understanding correctly, BMI doesn't require this internal change. BMI doesn't ever _require_ references to arrays to not change. For instance, the `get_value` method returns a copy of the data not a reference to the data. `get_value_ref` is not a BMI method but is used here as a convenience function, In fact, should be used with caution as it turns an output variable into a potential input variable. A `get_value_ref` exposes component implementation details that should probably remain private.

I would say it could be part of BMI++, though. It is definitely useful to have such a function as it reduces the number of copies when exchanging data between components. The `get_value_ref` that's exposed to the user should probably only work with input vars, though.

**Comment by mdpiper** [comment]
Thanks for this clarification, @mcflugen. I won't reopen this PR. Instead, I'll open a new PR where I'll implement properties for the output variables that are getting lost. This is still intrusive, but it follows the pattern used in [csdms/bmi-python](https://github.com/csdms/bmi-python), and it works with the existing BMI code. Plus, it may help with performance, since the arrays won't be recreated at each step.

**Comment by mperignon** [comment]
@mdpiper 's solution sounds reasonable. We know that this is a problem with the way pyDeltaRCM handles arrays, so let's fix that instead of building a workaround in BMI. It's an issue that's probably going to pop up with many other community-build models, though. I'm not sure what the solution for that is. Maybe csdms/bmi-python needs to be a bit more complex and explicitly deal with this issue. I'll wait for @mdpiper 's solution and see if I can create an example.

**Pull request closed without merging**
